### ISSUE TITLE
Chapter 3: add a part to convert on the fly CSV to GeoJSON

### ISSUE THREAD

**Issue by ThomasG77** [uwcartlab/webcartography#22]
It could use https://github.com/mapbox/csv2geojson

The point from this approach is publishing from spreadsheet to web without the need to make the conversion to GeoJSON manually. Useful to say people knowing only Excel/LibreOffice and not GeoJSON can publish without the GIS/Geospatial specialist. The sample could look more or less like the following

```javascript
fetch('path/to/file.csv').then(resp => res.text().then(text => {
  csv2geojson.csv2geojson(csvString, {
    latfield: 'LATFIELDNAME',
    lonfield: 'LONFIELDNAME',
    delimiter: ','
  }, function(err, data) {
    console.log(data)
  });
}
```

**Comment by reroth** [comment]
Thanks for sharing this! We will think about how to integrate in future code examples. We use the manual conversion in Lesson 3.1 because we aren't yet coding, just introducing web data formats. We wanted to students to get a feel how geojson as a file compares to shp, etc., a format they've learned in prior coursework (e.g., Introduction to GIS). We now include this link for sight recognition in Ch3 and use for more complex examples in the future (to be pushed Monday).
